### ISSUE TITLE
Making a library of this

### ISSUE THREAD

**Issue by suclearnub** [BlindJoker/quodlibet-discord-rpc#3]
I recently stumbled upon your code and found the IPC module very useful! Thanks :D 

I've made a fork of your code and made it into something that should be re-usable in other projects. [Check it out here](https://github.com/suclearnub/python-discord-rpc).

Wondering if you could help and make this something official for Discord?

**Comment by BlindJoker** [comment]
Hello there. 

The IPC module belongs entirely to the [SublimeDiscordRP](https://github.com/Snazzah/SublimeDiscordRP) project, so I can't take any credit for it.

I'm fine with contributing to the project, but I'm not sure if I can be of much help. Do you have anything in mind at the moment?

**Comment by suclearnub** [comment]
Reading the comments on the files, apparently there are some situations where an exception should be raised but isn't?

**Comment by BlindJoker** [comment]
The comments refer to exceptions that do get raised, but are not being handled as they should. They happen when either Discord is closed or when it gets restarted with Ctrl+R.
